[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/apollo-types",
    "projects/apollo-data",
    "projects/apollo-grammar",
    "projects/apollo-scene",
    "projects/apollo-layout",
    "projects/apollo-render",
    "projects/apollo-backend-svg",
    "projects/apollo-backend-wgpu",
    "projects/apollo",
]
exclude = [
    "projects/.DS_Store",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Aster <192607617@qq.com>"]
license = "MPL-2.0"

[workspace.dependencies]
apollo-types = { path = "projects/apollo-types" }
apollo-data = { path = "projects/apollo-data" }
apollo-grammar = { path = "projects/apollo-grammar" }
apollo-scene = { path = "projects/apollo-scene" }
apollo-layout = { path = "projects/apollo-layout" }
apollo-render = { path = "projects/apollo-render" }
apollo-backend-svg = { path = "projects/apollo-backend-svg" }
apollo-backend-wgpu = { path = "projects/apollo-backend-wgpu" }
apollo = { path = "projects/apollo" }
serde = { version = "1", features = ["derive"] }
wgpu = { version = "=24.0.5", default-features = true }
pollster = { version = "=0.4.0" }
bytemuck = { version = "=1.25.2", features = ["derive"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = "symbols"
panic = "abort"
