[package]
name = "apollo-backend-svg"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Apollo：SVG 矢量渲染后端"
publish = false

[dependencies]
apollo-types = { workspace = true }
apollo-scene = { workspace = true }
apollo-render = { workspace = true }

[dev-dependencies]
apollo-data = { workspace = true }
apollo-grammar = { workspace = true }

[lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"
